baseURL = "http://example.org/"
languageCode = "en-us"
title = "coding blog"
theme = "m10c"
author = "Lukas Rotermund"
description = "hobby coding blog about all dev topics that interest me"
avatar = "/assets/lukas-rotermund.jpg"
favicon = "/assests/favicon.ico"