baseURL = "https://lukasrotermund.de"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "coding blog"
theme = "lrotermund-cupper-hugo-theme"
enableRobotsTXT = true
enableGitInfo = true

[imaging]
  quality = 99

[menu]
  [[menu.nav]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 10
  [[menu.nav]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.nav]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.nav]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 40
  [[menu.nav]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"
    weight = 50
  [[menu.nav]]
    identifier = "data-protection"
    name = "Data Protection"
    url = "/data-protection/"
    weight = 60
  [[menu.nav]]
    identifier = "graphic-and-image-sources"
    name = "Graphic sources"
    url = "/graphic-and-image-sources/"
    weight = 70

[params]
  author = "Lukas Rotermund"
  description = "Backend Software Developer at tasko Products GmbH"
  homeMetaContent = "hobby coding blog about all dev topics that interest me"
  footer = "Made with [Hugo](https://gohugo.io/). Theme based on [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [K3s](https://k3s.io/)."
  dateFormat = "02.01.2006"
  #codePenUser = someUser
  katex = false
  hideHeaderLinks = false
  search = true
  showThemeSwitcher = true
  moveFooterToHeader = false
  logoAlt = "Thats me, Lukas Rotermund"
  avatar = "/assets/lukas-rotermund.jpg"
  favicon = "/assets/favicon.ico"
  [[params.social]]
    name = "Zettelkasten"
    url = "https://github.com/lrotermund/zettelkasten"
  [[params.social]]
    name = "github"
    url = "https://github.com/lrotermund"
    rel = "me"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lukas-rotermund"
    rel = "me"
  [[params.social]]
    name = "Mastodon"
    url = "https://social.tchncs.de/@lukasrotermund"
    rel = "me"
  [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
  definitionList = true
  footnote = true
  linkify = true
  strikethrough = true
  table = true
  taskList = true
  typographer = true

[markup.goldmark.parser]
  attribute = true
  autoHeadingID = true

[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xHTML = false

  [markup.highlight]
    codeFences = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
