baseURL = ""
languageCode = "en-us"
title = "coding blog"
theme = "m10c"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "imprint"
    name = "Imprint"
    url = "/imprint/"
    weight = 40
  [[menu.main]]
    identifier = "data-protection"
    name = "Data Protection"
    url = "/data-protection/"
    weight = 50

[params]
  author = "Lukas Rotermund"
  description = "hobby coding blog about all dev topics that interest me"
  avatar = "/assets/lukas-rotermund.jpg"
  favicon = "/assets/favicon.ico"
  [[params.social]]
    name = "github"
    url = "https://github.com/lrotermund"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lukas-rotermund"
  [[params.social]]
    name = "xing"
    url = "https://www.xing.com/profile/Lukas_Rotermund2"
  [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"